# Generated by Django 3.1.6 on 2021-06-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('otchestvo', models.CharField(max_length=40)),
                ('birthday', models.DateField()),
                ('parent_name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=40)),
                ('date_of_reference', models.DateField()),
                ('disabled', models.BooleanField()),
                ('have_many_children', models.BooleanField()),
            ],
        ),
    ]
