# Generated by Django 3.1.6 on 2021-06-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
